### PR TITLE
Adding Si4713_FM_RDS plugin

### PR DESCRIPTION
**Pull request by ShadowLight8**

### CODE REVIEW

**Comment by cpinkham** [comment]
Before we merge this, can you please add a 'platforms' array to the version section of your pluginInfo.json so that we can restrict the Plugin Manager UI to only displaying platform-compatible plugins?  If the plugin is not compatible with the BeagleBone systems, we do not want to display it in the list of installable plugins on those systems.

versions: [
    {
        minFPPVersion: "2.0",
        maxFPPVersion: "0",
        branch: "master",
        sha: "",
        platforms: [
            "Raspberry Pi"
        ]
    }
]

The platforms array field is currently not parsed, but I am working on a patch for master which would use this new field.  I also would look at backporting that patch to FPP v3.x when ready.

**Comment by ShadowLight8** [comment]
No problem. I'll add that in.

**Comment by dkulp** [comment]
Also note: I have no idea if this plugin will still work with the 4.0-alpha2 image.   We've removed a bunch of the Pi GPIO libraries since we don't use them anymore.  I don't know if that include the python pi GPIO stuff that this uses.      Not sure if you have a chance to test:  https://dankulp.com/fpp/

**Comment by ShadowLight8** [comment]
I'll check this out with the 4.0-alpha2 image.

**Comment by ShadowLight8** [comment]
I updated pluginInfo.json with the platforms array. Loaded up 4.0-alpha2 and used the updated pluginInfo.json to install the plugin without any issues. No problems getting the plugin up and running.

No problems around using GPIO. In Python, it's using "import RPi.GPIO" and on the command line, it is using "i2cget".

Let me know if there is anything else I should take a look at. Thanks!

**Comment by ShadowLight8** [comment]
@dkulp @cpinkham Platform array added and plugin looks good with the FPP 4 alphas. Following up if there is anything else I should take care of before this can be merged. Thanks!

**Pull request merged**
