### PR TITLE
Update pluginList.json

### PR DESCRIPTION
**Pull request by PiSignage**
Add fpp-jukebox

### CODE REVIEW

**Review by ghormann — APPROVED** [review]

**Comment by PiSignage** [comment]
Is there any idea when my plugin will be merged?

**Comment by patdelaney** [comment]
I merged it

**Comment by PiSignage** [comment]
Thank you so much for that. When will be shown on the plugin list?

**Comment by patdelaney** [comment]
I’ll check. But I think it’s it GitHub’s hands
To propagate it

**Comment by patdelaney** [comment]
I’ll take a look later

**Comment by ghormann** [comment]
I blieeve you raised the PR to the wrong spot.  Look at plugins.php in the main repo.  You need to change 

https://github.com/FalconChristmas/fpp-data/blob/master/pluginList.json

**Comment by PiSignage** [comment]
I have made a new pull request to the right repo

**Pull request merged**
